#!/bin/bash

#Author : Nathalie W
#Date : 2/20/23

### Sonarqube installation ###
# Sonarqube is an opensource platform devoloped by SonarSource#

echo "Switch to user vagrant " 
#su - vagrant

echo "Updating the system ..."
sleep 2
sudo yum update -y
echo "Installing Java ..."
sudo yum install java-11-openjdk-devel -y
sudo yum install java-11-openjdk -y

echo " Navigating to /opt directory"
cd /opt || exit

if [ ! -x /usr/bin/wget ] ;
then
    echo "installing wget"
sudo yum install wget -y
else 
    echo "wget is already installed"
fi
    echo "dowloading SonarQube ..."
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip

if [ ! -x /usr/bin/unzip ] ;
then
    echo "installing unzip"
sudo yum install unzip -y
sudo unzip /opt/sonarqube-9.3.0.51899.zip
else
    echo "unzip is already installed"
fi

    echo "Changing ownership to user vagrant and starting device..."
sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
cd /opt/sonarqube-9.3.0.51899/bin/linux-x86-64
#./sonar.sh start

 echo " Installing firewall... "
 sudo yum install firewalld

    echo "Opening port 9000"
firewalld-cmd --permanent --add-port=9000/tcp
firewalld-cmd --reload

    echo " You may now start SonarQube"
 
 #now you can paste you ip address in your browser, don't forget to add 9000!
